apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  # Variable de entorno
  MENSAJE_BIENVENIDA: "Hola, este es el cluster de Produccion"
  # Archivo de configuración
  custom.conf: |
    server {
        listen 8080;
        server_name localhost;
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configurado
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    env:
    - name: BIENVENIDA # Mapeamos la clave del ConfigMap a esta variable
      valueFrom:
        configMapKeyRef:
          name: web-config
          key: MENSAJE_BIENVENIDA
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config # El archivo aparecerá aquí
  volumes:
  - name: config-volume
    configMap:
      name: web-config
