apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-con-sondas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-health
  template:
    metadata:
      labels:
        app: web-health
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        # ¿Está la app lista para recibir tráfico?
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10 # Espera 10s antes de la primera prueba
          periodSeconds: 5
        # ¿Sigue la app viva o se ha colgado?
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3 # Si falla 3 veces, REINICIO.
