apiVersion: v1
kind: Secret
metadata:
  name: db-pass
type: Opaque
data:
  password: UzNjdXJlUEBzc3cwcmQ= # Base64 de S3cur3P@ssw0rd
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-seguro
spec:
  containers:
  - name: app-container
    image: alpine:latest
    command: ["sleep", "3600"]
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-pass
          key: password
